services:
  odoo:
    image: odoo:19.0
    container_name: odoo-app
    environment:
      - HOST=db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${ODOO_PORT}:8069"
    volumes:
      - odoo-app-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    depends_on:
      - db
    command: odoo -d ${POSTGRES_DB} --db_user=${POSTGRES_USER} --db_password=${POSTGRES_PASSWORD} -i base --addons-path=/mnt/extra-addons -u estate --dev xml

  db:
    image: postgres:18.0-alpine
    container_name: odoo-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-app-data:
  odoo-db-data: